title: Lisa Elliott
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.008960574
  brandStrength: 0.6917562
  lightness: 0.9677419
  brandColors:
    - '#104a3e'
    - '#df7f19'
    - '#e0d03f'
    - '#7cbc28'
    - '#538429'
  rhythmicContrast: 0.2580645
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: lisaelliott
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.60463
layout_spectrum: 0.9749104
