name: lisaelliott
favicon: null
layout_spectrum: 0.73611
typography_spectrum: 0.60463
title: Lisa Elliott
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afc0dc'
    - '#8b7464'
    - '#97969b'
    - '#e0edfe'
    - '#62514c'
  brandStrength: 0.6875
  lightness: 0.748212062753737
  saturation: 0.22644065716303885
  rhythmicContrast: 0.9267973881214857
purpose: []
