name: lisaelliott
favicon: null
layout_spectrum: 0.73611
typography_spectrum: 0.60463
title: Lisa Elliott
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#104a3e'
    - '#df7f19'
    - '#e0d03f'
    - '#7cbc28'
    - '#538429'
  brandStrength: 0
  lightness: 0.748212062753737
  saturation: 0.22644065716303885
  rhythmicContrast: 0.9267973881214857
purpose: []
